[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
