[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/menu"
  to = "/customer/menu.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/customer/book.html"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/customer/reviews.html"
  status = 200

[[redirects]]
  from = "/points"
  to = "/customer/points.html"
  status = 200

[[redirects]]
  from = "/manage"
  to = "/customer/manage.html"
  status = 200

[[redirects]]
  from = "/manager"
  to = "/manager/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
